spring:
  application:
    name: eureka-server
server:
  port: 8761 #eureka는 약속된 지정 포트번호가 있다 = 8761
eureka:
  client:
#    eureka서버가 자기 자신은 eureka에 등록하지 않겠다라는 설정
    register-with-eureka: false
    fetch-registry: false
